name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'cmd/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use docker compose to build web service
      run: |
        echo "building server app image using docker compose..."
        docker compose build app
        echo "done building..."
    - name:  Upload image to dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME}}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_LOGIN_PW }}
      run: |
        echo "listing all images"
        docker images
        echo "renaming image"
        docker tag flexiexpensesmanager_backend-app charmflex/fem-app
        echo "login to dockerhub"
        docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
        echo "push to dockerhub"
        docker push charmflex/fem-app
