name: Docker Image CI

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use docker compose to build app service
      run: |
        echo "building web image using docker compose..."
        docker compose build app
        echo "done building..."
    - name:  Upload image to dockerhub
      run: |
        echo "listing all images"
        docker images
        echo "renaming image"
        docker tag flexiexpensesmanager_backend-app charmflex/fem_server
        echo "login to dockerhub"
        docker login --username ${{ secrets.DOCKER_LOGIN_USERNAME }} --password ${{ DOCKER_LOGIN_PW }}
        echo "push to dockerhub"
        docker push charmflex/fem_server
      
