name: Docker Image CI

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v3
    - name: Replacing placeholders of application properties
      run: |
        sed -i 's|${DATABASE_USERNAME}|${{ secrets.DATABASE_USERNAME }}|g' src/main/resources/application.properties
        sed -i 's|${DATABASE_PASSWORD}|${{ secrets.DATABASE_PASSWORD }}|g' src/main/resources/application.properties
    - name: Use docker compose to build app service
      run: |
        echo "building web image using docker compose..."
        docker compose build app
        echo "done building..."
    - name:  Upload image to dockerhub
      run: |
        echo "listing all images"
        docker images
        echo "renaming image"
        docker tag flexiexpensesmanager_backend-app charmflex/fem_server
        echo "login to dockerhub"
        docker login --username ${{ secrets.DOCKER_LOGIN_USERNAME }} --password ${{ secrets.DOCKER_LOGIN_PW }}
        echo "push to dockerhub"
        docker push charmflex/fem_server
      
