name: Update and Restart App Service

on:
  workflow_dispatch

jobs:

  app-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Execute SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DO_SSH_PW }}
          script: |
            echo "testing"
            cd fem_server
